Add update_json provider
rheinwerk-verlag/pganonymize pull request #52
Opened 2024-02-27 19:44 UTC by bobslee

This provider will replace json and jsonb data values with a specified provider configuration per data type.

2024-02-28 07:50 UTC, bobslee commented
@hkage Please can you check out this PR?
I added tests (all succeed) and tested manually (it works).
We need this feature very soon, to install from PyPi.

2024-02-28 09:33 UTC, hkage commented
@bobslee Thanks for the contribution! I will take a look as soon as I can.

2024-02-28 16:12 UTC, hkage requested changes
Everything else looks good to me. And thanks again for your work and especially the tests and documentation.

2024-02-28 16:22 UTC, hkage commented on pganonymize/providers.py
> +                    val_update = update_values_type.get(val_type)
On the other hand in the sense of the anonymization no value would be forgotten.

2024-02-28 19:08 UTC, bobslee commented on docs/schema.rst
> +                        name: uuid
Done, see 29944ed

2024-02-28 19:11 UTC, bobslee commented on pganonymize/providers.py
> +                    val_update = update_values_type.get(val_type)
Thanks, your're totally right! I missed this circumstance.
I added a test: `test_type_not_specified`.
It was indeed a bug and it's fixed now.

The implementation is consistent with the `pganonymize` design - which means:
Fields that are not present in the schema are not anonymized and retain their original status (value).

2024-02-28 19:12 UTC, bobslee commented
> Everything else looks good to me. And thanks again for your work and especially the tests and documentation.

Thanks and it was my pleasure!

2024-02-29 06:46 UTC, merged

2024-02-29 06:57 UTC, hkage commented
I published the new release, version 0.11.0 - thanks again for your contribution.

Don't mind the failing tests - the Python 2.7 tests don't work anymore, because the Ubuntu image dropped the binary. But the tests were successful on my workstation using a pyenv environment. As we still need Python 2.7 support I will fix this issue with the test setup in a separate pull request.

2024-02-29 07:05 UTC, bobslee commented
You're welcome and thank you for your quick and decent follow-up.
By the way, I tested in a Python 3.8.11 env.

2024-02-29 07:10 UTC, bobslee commented
@hkage When will the documentation be updated?
https://pganonymize.readthedocs.io/en/latest/

2024-02-29 07:17 UTC, hkage commented
I use a webhook from Read the Docs, but it seems to be broken. Maybe because GitHub changed the permissions or the key is deactivated. I will check this.

2024-02-29 07:45 UTC, hkage commented
The documentation is now up to date. The project was missing the now required `readthedocs.yml` and the last successful documentation build was 1 year ago, so a lot has changed on the RTD side since then. Thanks for reporting.